### ISSUE TITLE
Create a stream field map block

### ISSUE THREAD

**Issue by marteinn** [Frojd/wagtail-geo-widget#1]

**Comment by SalahAdDin** [comment]
What's about this?
I asked in the `Wagtail Google Groups Forum` about this question today, i'm waiting about answer.

**Comment by marteinn** [comment]
Hi @SalahAdDin! I have not yet begun work on this feature, but my guess is that it might be developed, tested and out within the next 1-2 months.

**Comment by SalahAdDin** [comment]
Wow, is very long time.

**Comment by marteinn** [comment]
@SalahAdDin Sorry about that, but you are of course welcome with a pull request :)

**Comment by marteinn** [comment]
@SalahAdDin This is now included in https://github.com/Frojd/wagtail-geo-widget/commit/cf573c4bec897311fffc0144719b520eb15b7d9b

**Comment by SalahAdDin** [comment]
@marteinn Thank you very much,
