### ISSUE TITLE
Create a pypi package

### ISSUE THREAD

**Issue by emorozov** [Frojd/wagtail-geo-widget#10]
Please, create a pypi package for easier installation of wagtail-geo-widget.

**Comment by marteinn** [comment]
Hi @emorozov! The package is already om pypi under the name wagtailgeowidget and the pip command are mentioned in the readme. Do you have issues installing the package?

**Comment by marteinn** [comment]
Pypi page: https://pypi.python.org/pypi/wagtailgeowidget

**Comment by emorozov** [comment]
Sorry, I was inattentive and was trying to install `wagtail-geo-widget` instead.
