### ISSUE TITLE
Widget not rendering in Wagtail 3.0, but works in Wagtail 2.16.2.

### ISSUE THREAD

**Issue by dino8890** [Frojd/wagtail-geo-widget#108]
It seems the widget is not working correctly in Wagtail 3.0. I have tested the basic setup for both 3.0 and 2.16.2, and it does not render properly at 3.0, but works fine for 2.16.2 version.

Notice the difference between placeholder values in the fields, they're missing in 3.0.

Wagtail 3.0
![3-0](https://user-images.githubusercontent.com/17911579/170233306-3df910ff-f5d7-41bf-8c02-368aa24aaa2f.png)

Wagtail 2.16.2
![2-16-2](https://user-images.githubusercontent.com/17911579/170233329-e6a45549-b654-491f-ae14-b84668845b15.png)

```py
class MapTestPage(Page):
    map_address = CharField(max_length=250, blank=True, null=True)
    map_location = CharField(max_length=250, blank=True, null=True)
    map_zoom = SmallIntegerField(blank=True, null=True)

    content_panels = Page.content_panels + [
        MultiFieldPanel([
            GeoAddressPanel('map_address', geocoder=GOOGLE_MAPS),
            GoogleMapsPanel('map_location', address_field='map_address', zoom_field='map_zoom'),
            FieldPanel('map_zoom'),
        ], 'Location'),
    ]

```

**Comment by marteinn** [comment]
Thanks @dino8890 for reporting this issue, I have some time reserved for Wagtail 3 upgrades for other Wagtail packages, will include this in that work. Will report back here once upgrade is complete.

**Comment by hallpower** [comment]
@marteinn first of all, thanks for this brilliant widget and your work in maintaining it! 

Do you already have an ETA on >3.0 compatibility? I took a look to figure out obvious fixes, but nothing jumped out at me...

**Comment by marteinn** [comment]
Hi @hallpower and @dino8890! Just wanted to let you know that https://github.com/Frojd/wagtail-geo-widget/releases/tag/v6.2.0 is out now with official Wagtail 3.0 support. Please give it a go and if you see any bugs please create new issues :)

**Comment by hallpower** [comment]
@marteinn Super! Thanks so much! Everything working as it should!
