### ISSUE TITLE
GoogleMapsPanel doesn't correctly parse the passed in address_field

### ISSUE THREAD

**Issue by nickmoreton** [Frojd/wagtail-geo-widget#109]
https://github.com/Frojd/wagtail-geo-widget/blob/d5fa15e3c44be2c047e6721904d0d82e4ffb4251/wagtailgeowidget/edit_handlers.py#L14

I've not had time to dig very deeply into the issue but I think it's because the recent work to add Wagtail compatibility has broken it.

If get time I will take a look. This part of the upgrade docs is the relevant info: https://docs.wagtail.org/en/stable/releases/3.0.html#api-changes-to-panels-edithandlers

It may be as simple as renaming this function: https://github.com/Frojd/wagtail-geo-widget/blob/d5fa15e3c44be2c047e6721904d0d82e4ffb4251/wagtailgeowidget/edit_handlers.py#L29 as I think above where https://github.com/Frojd/wagtail-geo-widget/blob/d5fa15e3c44be2c047e6721904d0d82e4ffb4251/wagtailgeowidget/edit_handlers.py#L26
Is not using the function below but the function on the parent Panel class which returns and empty dict. I am guessing though.

**Comment by nickmoreton** [comment]
I'll close this issue now as I realised the error was caused by the order of fields in my panels and not the above

**Comment by marteinn** [comment]
@nickmoreton 👍 Thanks for the update! (And sorry for the late reply)
