### ISSUE TITLE
Wagtail 4 compatibility: FieldPanel Permissions

### ISSUE THREAD

**Issue by unicode-it** [Frojd/wagtail-geo-widget#114]
Wagtail 4 added FieldPanel permissions instead of overriding edit_handlers (https://docs.wagtail.org/en/stable/reference/pages/panels.html#field-panel). The FieldPanels provided by this project don't support this functionality. They shadow permissions attribute set on the FieldPanel.
A solution is proposed here #113

**Comment by marteinn** [comment]
Suggested changes has been accepted and this issue has been resolved in https://github.com/Frojd/wagtail-geo-widget/releases/tag/v7.0.0, closing.
