### ISSUE TITLE
The geos_ptrn should allow minus as well

### ISSUE THREAD

**Issue by dpetrov** [Frojd/wagtail-geo-widget#14]
Using the Google Maps API, some location might have negative longitude. The geos_ptrn will fail in that case and map won't reflect the real coordinates.

I think that something like that, might do it:

geos_ptrn = re.compile(
    "^SRID=([0-9]{1,});POINT\(([0-9\.\-]{1,})\s([0-9\.\-]{1,})\)$"
)

**Comment by marteinn** [comment]
Hi @dpetrov! Thanks for the bug report, will look into it as soon as possible.

**Comment by marteinn** [comment]
Solved in 49756d80b2a433f865b9d36433fe6865d41d18ad
