### ISSUE TITLE
Allow for configurable default value

### ISSUE THREAD

**Issue by WoLpH** [Frojd/wagtail-geo-widget#2]
It seems the only way to change the default map right now is by passing along a default value to the model field. In some cases it's preferable to not have a default so you can keep it blank.

**Comment by marteinn** [comment]
Thanks for filing an issue @WoLpH! If I understand you correctly, you would prefer a app setting that defines a default location, and passing a location in the field would override that value?

**Comment by WoLpH** [comment]
A global app setting would do the trick for me. Although I'd think being
able to set it from the GeoPanel constructor would be a very obvious place
as well.

**Comment by marteinn** [comment]
Awesome! Will put it on the roadmap and try to do a release in the upcoming weeks.

**Comment by WoLpH** [comment]
Great! Thanks :)

It would make the widget a lot more useful for people not living in Stockholm ;)

**Comment by marteinn** [comment]
Just wanted to let you know that 1.1.0 (d9851b72f067b3d2200a604cb4726f06be2bd3d4) includes the `GEO_WIDGET_DEFAULT_LOCATION` setting, that accepts a dict with lat/lng values.

Example:

```python
GEO_WIDGET_DEFAULT_LOCATION = {'lat': 48.208174, 'lng': 16.373819}  # Vienna
```

Thanks for the feedback @WoLpH!

**Comment by WoLpH** [comment]
Thanks for the quick fix! I'll install it ASAP :)
