### ISSUE TITLE
Django2 Support?

### ISSUE THREAD

**Issue by elcolie** [Frojd/wagtail-geo-widget#26]
Is your package support Django2?

**Comment by marteinn** [comment]
@elcolie Sure thing! The latest release (v4.0.1) is build to work on Wagtail 2.0 and Django 2.0.

If you want to use Wagtail 1.13 and Django 2.0, please look at this info: https://github.com/Frojd/wagtail-geo-widget#this-library-no-longer-works-on-wagtail-113-lts

**Comment by elcolie** [comment]
Thank you :)

**Comment by marteinn** [comment]
@elcolie Lets us know if you stumble upon any bugs 👍
