### ISSUE TITLE
GEO_WIDGET_ZOOM not working

### ISSUE THREAD

**Issue by eduardocp** [Frojd/wagtail-geo-widget#27]
I have defined GEO_WIDGET_ZOOM to 15 on settings but the map not respect it.

I belive it's becouse the file `edit_handlers.py` on line 21 no call the constant.

**Comment by marteinn** [comment]
Thanks for the PR @eduardocp! Will review and run some tests today or tomorrow.

**Comment by marteinn** [comment]
Accepted and fixed in https://github.com/Frojd/wagtail-geo-widget/releases/tag/v4.0.2, thanks for the help @eduardocp!
