### ISSUE TITLE
Option to hide coordinate fields

### ISSUE THREAD

**Issue by eduardocp** [Frojd/wagtail-geo-widget#30]
I think it would be nice to have the option of displaying or not the coordinate field

**Comment by marteinn** [comment]
Good suggestion @eduardocp, will include it in the next release!

**Comment by marteinn** [comment]
Included in https://github.com/Frojd/wagtail-geo-widget/releases/tag/v4.0.5. This feature only works on the GeoPanel (not the streamfield block)
