### ISSUE TITLE
Failed to pip install with python3

### ISSUE THREAD

**Issue by pyMan** [Frojd/wagtail-geo-widget#32]
`pip install wagtailgeowidget==4.0.2`

`
 Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-mb8vp6hq/wagtailgeowidget/setup.py", line 10, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'
`

This seems to happend with pip 10
See [here ](https://stackoverflow.com/a/49867265) for a possible solution

**Comment by marteinn** [comment]
Thanks for the issue @pyMan. I have this issue on other packages that I have solved by hard-coding dependencies in setup.py. Will try to have a fix and release up in a couple of hours.

**Comment by marteinn** [comment]
Solved in https://github.com/Frojd/wagtail-geo-widget/commit/de13588a77b4a3eec456df987600c513c018868f and pushed on pypi
