### ISSUE TITLE
Cannot geocode on production 

### ISSUE THREAD

**Issue by kyale-mwendwa** [Frojd/wagtail-geo-widget#35]
When i run the service on my laptop/dev enviroment it works just fine. However when I deploy it on my production Debian server it shows the following error when typing in an address in a warning box just below the input.

"Could not geocode address "a". The map may not be in sync with the address entered."

When i check the console i get the following error.

Geocoding Service: This API project is not authorized to use this API.  
For more information on authentication and Google Maps JavaScript API services please see: https://developers.google.com/maps/documentation/javascript/get-api-key

The strange part is, the map displays so it partially works. 

They are both running same setup
1. Django 2.0.9
2. Wagtail 2.1.3
3. Python 3.4.2

![image](https://user-images.githubusercontent.com/10475981/47219638-05d3a600-d3b8-11e8-9afb-8e274439b5ac.png)
 or sometimes it shows this pop up

![image](https://user-images.githubusercontent.com/10475981/47220355-39afcb00-d3ba-11e8-8803-d86c79c10da9.png)

**Comment by marteinn** [comment]
Hi @kyale-mwendwa, this looks like you are missing av api key for google maps. Any project you put in production using google maps requires a google maps key. That key in return, also requires that you put your live domain into a domain whitelist.

**Comment by kyale-mwendwa** [comment]
There is a map's key is available hence the display of the map and the IP has been whitelisted.

**Comment by marteinn** [comment]
But the issue is still "Geocoding Service: This API project is not authorized to use this API.", right?
