### ISSUE TITLE
Django 2.1 breaks GeoField.render() method

### ISSUE THREAD

**Issue by jwayodi** [Frojd/wagtail-geo-widget#37]
Django 2.1 removes support for `Widget.render()` methods without the `renderer` argument (https://github.com/django/django/commit/2bd207ada0367debe8c8e298203435d5c88c14bd), which breaks `GeoField.render()`.

I have made a PR (#36) that fixes this.

**Comment by kutenai** [comment]
Hey -- would be nice to have this fix in. 
I've forked the repo so I can apply the patch for myself, but an official fix would be nice.

**Comment by marteinn** [comment]
I just released 4.0.4 on pypi, please try it out and let me know if it works!

**Comment by jwayodi** [comment]
> I just released 4.0.4 on pypi, please try it out and let me know if it works!

It works. Thanks a lot!
