### ISSUE TITLE
GeoPanel inside InlinePanel

### ISSUE THREAD

**Issue by Alexandre27** [Frojd/wagtail-geo-widget#4]
When the GeoPanel is used inside an InlinePanel it is not rendered and it breaks the inlinepanel behaviour.
![screen shot 2017-03-21 at 12 58 12](https://cloud.githubusercontent.com/assets/3704961/24151140/c7f3d182-0e3f-11e7-88ce-1bdccad6f0ad.png)

**Comment by marteinn** [comment]
Thanks for the issue @Alexandre27! Investigating now.

**Comment by marteinn** [comment]
Support for InlinePanel is now included in the v2.0.0 release (62e763ec45505add81e352fb9198670f59fc870b). Thanks for the help!
