### ISSUE TITLE
Problem with GEO Django library.

### ISSUE THREAD

**Issue by SalahAdDin** [Frojd/wagtail-geo-widget#8]
I have this problem:
![seleccion_308](https://cloud.githubusercontent.com/assets/5034215/24615262/7c9fdc6a-1896-11e7-89ba-1cf889091fbc.png)

THis happend after i save the field. I didn't add the setting because i don't need it, i only want put the address and see the map, no more.

Field and Stream Block works fine before save de field, but after it, when page is reloaded, or accessed again, i get this error.

I found this [documentation](https://docs.djangoproject.com/en/1.10/ref/contrib/gis/install/geolibs/#troubleshooting).

What can i do?

**Comment by marteinn** [comment]
Originally this lib had a geodjango requirement, this looks like a remnant of it. Will kick off a clean docker (without spatial) and look into it. Thanks for reporting!

**Comment by marteinn** [comment]
@SalahAdDin I just managed to recreate the bug, looking into a solution now. Was the GeoDjango deps as I thought.

**Comment by marteinn** [comment]
This c2adc22028206dd60a057d70199af92dc304e804 should solve this issue

**Comment by SalahAdDin** [comment]
I foun the problem in the widget, review it.... but you did, thank you!
I'll test it now!
