### ISSUE TITLE
Set zoom level dynamically from a GeoPanel

### ISSUE THREAD

**Issue by m5seppal** [Frojd/wagtail-geo-widget#85]
Currently it's possible to zoom in and out the map widget, but after you save the map and open it again for edit, last zoom level in the map widget is not preserved but instead the hardcoded zoom level is used (either from settings or GeoPanel(zoom=...)).

What I need is to set the zoom level dynamically for each map, so that different maps can use different zoom levels. When I save the map, I want to read the "zoom" from map widget and store it to the database for the map. When the map is opened for edit, GeoPanel should read "zoom" from the database and initialise the widget with that zoom level instead of the default one. Optionally, there could be also "zoom" field shown in the edit page if user wants to set it via text input instead of using the map.

**Comment by vladox** [comment]
Hi @marteinn please have a look, I've also updated the docker-compose for the nonspatial configuration to run without using make.
So far it's been working correctly.

**Comment by marteinn** [comment]
Hi @m5seppal and @vladox! I decided to not accept the PR (my reasoning here https://github.com/Frojd/wagtail-geo-widget/pull/91#issuecomment-1004825354) and instead do my own take on it. As of [v5.3.0](https://github.com/Frojd/wagtail-geo-widget/releases/tag/v5.3.0) it is now possible to have a persistent zoom by using a separate zoom field, it works in a similar way as the address field and works no matter if the field is a spatial field or regular string. The commit containing this feature can be found here: https://github.com/Frojd/wagtail-geo-widget/commit/eefcc73e916a9eda68229e086b19eb46b505f749

With this I'm closing this issue.
