### ISSUE TITLE
Fake function in documentation

### ISSUE THREAD

**Issue by SalahAdDin** [Frojd/wagtail-geo-widget#9]
Hi man, all is well, but you have a big problem here: `parse_geosgeometry_string`.

This function doesn't exist, i get this problem:
![seleccion_309](https://cloud.githubusercontent.com/assets/5034215/24634298/cebfd7b8-18d5-11e7-991c-3a8233ca3c6f.png)

So, viewing if something is wrong i found that these function doesn't exist.

I think you have to change documentation.

PD: Which the difference between spatial and nonspatial examples?

**Comment by marteinn** [comment]
I did a last minute refactoring of the geosgemoetry string parser, which I renamed `parse_geosgeometry_string` to `geosgeometry_str_to_struct`, but missed some areas of docs/examples. Release 3.1.1 (87deb0974f2a602c9d8b5f989209a4310a1fbb5a) solves this.
